### ISSUE TITLE
[Feature request] follow and non-follow Logs

### ISSUE THREAD

**Issue by tuxflo** [MartinRamm/fzf-docker#15]
Hi!
At first: I'm a huge fan of your script, make my live way easier when dealing with docker stuff.
I wonder if it is possible to create two separate versions of the `dl` command as follows:
* `dlf`: does what currently `dl` does (logs in follow mode)
* `dl` does not automatically follow (no `-n` in the docker logs command) but is able to handle  some additional commands (if providedf)

Why?
Sometimes I want to grep for certain stuff in the logs like
`docker logs mycontainer | rg 'ERROR'`
Now it would be great if I could use the fzf magic for selecting the container but still be able to append the ripgrep (or any other command).

So the workflow could look like this:
* `dl | rg 'ERROR'`
* fzf opens
* container can be fuzzy selected
* only the lines containing ERROR are shown

I already took a look into the source code of fzf-docker to provide an PR for this but don't really get what the subshell and sed stuff is doing in the `__docker_logs` function.

**Comment by MartinRamm** [comment]
Hi @tuxflo,

Glad to hear you are using this project and thank you very much for your suggestion.

I am having a bit of trouble following your thoughts here. Using `rg`(or `grep` or similar) should work as you explained in your workflow, even if the logs are opened in follow mode. At  least that is what my system (tested with bash and zsh on nix-os) does:
![dl](https://user-images.githubusercontent.com/31626748/206042184-ddb16c5b-8781-4ae1-9702-b37822c36715.gif)

I assume this doesn't work for you? If yes, I need to be able to reproduce the problem. Please provide all information listed on the bug-report issue template, then I am happy to help.

Thanks,

-Martin

P.S.: The complexity you saw in the `__docker_logs` function comes from the fact that `docker` only allows you to open the logs of one container at a time. This makes selecting more than one container and displaying the logs (in the correct order, prepended with the container name) quite a difficult thing...

**Comment by tuxflo** [comment]
Hi!
Your answer totally solves my needs, I just did not expect that it's working like that :see_no_evil: 
Also thanks for explaining what the `__docker_logs` function is doing.
And also some bonus points for using NixOS :sunglasses:
